version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nsfw-nest-gpu-dev
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ['gpu']
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - TZ=Asia/Seoul
      - NODE_ENV=development
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
